import numpy as np  # Import the NumPy library for numerical operations and array handling
from matplotlib import pyplot as plt  # Import Matplotlib's pyplot for creating plots and charts
from scipy.signal import firwin, lfilter  # Import FIR filter design (firwin) and digital filtering (lfilter) from SciPy

# ----------------------------------------------------
# Parameters
# ----------------------------------------------------
N = 2560 # Set the number of OFDM subcarriers (size of the FFT)
M = 16  # Set the QAM modulation order (e.g., 16-QAM)
L = 4  # Set the Oversampling factor (OFDM size is multiplied by L in time domain)
N_iter = 5  # Set the number of clipping-filter iterations (for iterative C&F)
CR = 1.5  # Set the Clipping Ratio (threshold factor: A = CR * sqrt(P_avg))
num_symbols = 10000  # Set the number of OFDM frames/symbols to simulate for CCDF statistics
filter_order = 64  # Set the order (length minus 1) of the FIR low-pass filter (LPF)


# ----------------------------------------------------
# QAM Modulation
# ----------------------------------------------------
def qam_mod(bits):  # Define function to map input bits to complex QAM symbols
    m = int(np.log2(M))  # Calculate number of bits per symbol (e.g., 4 for 16-QAM)
    gray = bits.reshape(-1, m)  # Reshape the flat bit stream into groups of 'm' bits
    k = gray[:, 0] * 8 + gray[:, 1] * 4 + gray[:, 2] * 2 + gray[:, 3] * 1  # Simple conversion to decimal index (Assumes 4 bits, but not strict Gray)
    r = 2 * ((k % 4) - 1.5)  # Calculate the Real (In-phase) component value based on index
    i = 2 * ((k // 4) - 1.5)  # Calculate the Imaginary (Quadrature) component value based on index
    x = (r + 1j * i) / np.sqrt(10)  # Create the complex symbol and normalize its power (sqrt(10) is for 16QAM)
    return x  # Return the array of complex QAM symbols


# ----------------------------------------------------
# OFDM Mod/ Demod
# ----------------------------------------------------
def ofdm_mod(symbols):  # Define function for OFDM modulation (IFFT with oversampling)
    symbols_oversampled = np.concatenate(
        [symbols, np.zeros((L - 1) * N)])  # Zero-pad the symbols in frequency domain for oversampling
    return np.fft.ifft(symbols_oversampled)  # Perform Inverse Fast Fourier Transform (IFFT) to get time domain signal


# ----------------------------------------------------
# Safe Clipping
# ----------------------------------------------------
def clip_signal(x, CR):  # Define function to perform hard clipping on the time-domain signal
    A = CR * np.sqrt(
        np.mean(np.abs(x) ** 2))  # Calculate the clipping amplitude threshold A based on CR and average power
    eps = 1e-12  # Define a small epsilon to prevent division by zero in the next step
    return np.where(np.abs(x) > A, A * x / (np.abs(x) + eps),
                    x)  # Clip samples: if |x|>A, set magnitude to A, keeping the phase


# ----------------------------------------------------
# LPF for filtering clipping noise
# ----------------------------------------------------
def make_filter():  # Define function to design the Low-Pass Filter (LPF)
    return firwin(filter_order + 1, 1 / L)  # Design a linear-phase FIR LPF with a cutoff frequency normalized to 1/L
    # The cutoff of 1/L cancels the out-of-band noise generated by clipping


def filter_signal(x, h):  # Define function to apply the designed filter to a signal
    return lfilter(h, 1,
                   x)  # Apply the FIR filter 'h' to the signal 'x' (1 is for the denominator of the transfer function)


# ----------------------------------------------------
# PAPR Calculation
# ----------------------------------------------------
def papr(x):  # Define function to calculate PAPR in dB
    return 10 * np.log10(
        np.max(np.abs(x) ** 2) / np.mean(np.abs(x) ** 2))  # Calculate 10*log10(Peak Power / Average Power)


# ----------------------------------------------------
# CCDF
# ----------------------------------------------------
def ccdf(values):  # Define function to calculate the Complementary Cumulative Distribution Function (CCDF)
    values_sorted = np.sort(values)  # Sort the input PAPR values in ascending order
    ccdf_vals = 1 - np.arange(len(values_sorted)) / len(values_sorted)  # Calculate 1 - CDF (cumulative distribution)
    return values_sorted, ccdf_vals  # Return the sorted PAPR values (x-axis) and the CCDF values (y-axis)


# ----------------------------------------------------
# Simulation
# ----------------------------------------------------
h = make_filter()  # Design and store the filter impulse response

papr_original = []  # Initialize list to store PAPR values of the original (unclipped) signal
papr_iters = [[] for _ in range(N_iter)]  # Initialize a nested list to store PAPR values for each iteration of C&F

for _ in range(num_symbols):  # Start the simulation loop over the specified number of OFDM symbols
    bits = np.random.randint(0, 2, N * int(np.log2(M)))  # Generate a block of random bits for one OFDM symbol
    qam = qam_mod(bits)  # Modulate the bits into QAM symbols
    s = ofdm_mod(qam)  # Perform OFDM modulation (IFFT with oversampling)

    papr_original.append(papr(s))  # Calculate and store the PAPR of the original signal

    x = s.copy()  # Create a copy of the original signal for the iterative process

    for k in range(N_iter):  # Start the loop for iterative Clipping and Filtering
        # CLIPPING
        x = clip_signal(x, CR)  # Apply the hard clipping function

        # FILTERING
        x = filter_signal(x, h)  # Apply the LPF to suppress out-of-band noise caused by clipping

        # Save iteration PAPR
        papr_iters[k].append(papr(x))  # Calculate and store the PAPR after this iteration of C&F

# ----------------------------------------------------
# Compute PAPR statistics vs iterations
# ----------------------------------------------------
mean_papr = []  # Initialize list for mean PAPR after each iteration
median_papr = []  # Initialize list for median PAPR after each iteration
max_papr = []  # Initialize list for max PAPR after each iteration

for k in range(N_iter):  # Loop through the results of all iterations
    mean_papr.append(np.mean(papr_iters[k]))  # Calculate the mean of PAPR values for iteration k
    median_papr.append(np.median(papr_iters[k]))  # Calculate the median of PAPR values for iteration k
    max_papr.append(np.max(papr_iters[k]))  # Calculate the maximum of PAPR values for iteration k

# Also compute original
orig_mean = np.mean(papr_original)  # Calculate the mean PAPR of the original signal
orig_median = np.median(papr_original)  # Calculate the median PAPR of the original signal
orig_max = np.max(papr_original)  # Calculate the maximum PAPR of the original signal

# ----------------------------------------------------
# Plot PAPR statistics vs iterations
# ----------------------------------------------------
iterations = np.arange(1, N_iter + 1)  # Create x-axis values for the plot (1 to N_iter)

plt.figure(figsize=(10, 6))  # Create a new plot figure with a specific size
plt.plot(iterations, mean_papr, 'o-', label="Mean PAPR")  # Plot the mean PAPR reduction over iterations
plt.plot(iterations, median_papr, 's-', label="Median PAPR")  # Plot the median PAPR reduction over iterations
plt.plot(iterations, max_papr, 'd-', label="Max PAPR")  # Plot the max PAPR reduction over iterations

# Add original value as horizontal baseline
plt.axhline(orig_mean, color='gray', linestyle='--',
            label="Original Mean")  # Draw horizontal line for original mean PAPR
plt.axhline(orig_median, color='gray', linestyle='-.',
            label="Original Median")  # Draw horizontal line for original median PAPR
plt.axhline(orig_max, color='gray', linestyle=':', label="Original Max")  # Draw horizontal line for original max PAPR

plt.xlabel("Iteration Number")  # Set the x-axis label
plt.ylabel("PAPR (dB)")  # Set the y-axis label
plt.title("PAPR Statistics vs Clipping–Filtering Iterations")  # Set the plot title
plt.grid(True)  # Enable grid lines on the plot
plt.legend()  # Display the legend
plt.show()  # Display the first plot (PAPR statistics)

# Plot CCDF curves
# ----------------------------------------------------
plt.figure(figsize=(10, 6))  # Create a second plot figure

# Original CCDF
papr_o, ccdf_o = ccdf(papr_original)  # Calculate the CCDF for the original signal
plt.semilogy(papr_o, ccdf_o, label="Original")  # Plot the original CCDF on a semi-log scale

# Each iteration CCDF
for k in range(N_iter):  # Loop through all C&F iterations
    pi, ci = ccdf(papr_iters[k])  # Calculate the CCDF for the result of iteration k
    plt.semilogy(pi, ci, label=f"Iteration {k + 1}")  # Plot the CCDF for the current iteration

plt.grid(True, which='both')  # Enable grid lines
plt.xlabel("PAPR (dB)")  # Set the x-axis label
plt.ylabel("CCDF")  # Set the y-axis label
plt.title("PAPR CCDF – Multi-Iteration Clipping & Filtering")  # Set the plot title
plt.legend()  # Display the legend
plt.show()  # Display the second plot (CCDF curves)